### ISSUE TITLE
Create the custom menu

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/asteol.wordpress.theme#4]
Display the menu as follows :

- [x] In a left column from 1024px screen width
- [x] In a collapsed menu under 1024px screen width. Here is an example of the collapsed menu we look for: http://wp.asteol.fr/ 
- [x] the menu must allow navigating down lower levels of a primary menu by hovering the menu or tapping the menu, depending on the device used.

**Comment by gsouvik** [comment]
**Update**
Got it opened again, sorry for the confusion. 

@JeremieLitzler I closed this issue by error, please keep it opened, I cannot find an option to do so.

**Comment by WebDevJL** [comment]
@gsouvik : let me know when I can review your work by creating the PR.

**Comment by gsouvik** [comment]
@WebDevJL I pushed a bit of changes yesterday and asked some questions in that commit. Will push more updates tonight. It will have mostly all the features. This would be an ongoing process.

**Comment by WebDevJL** [comment]
@gsouvik : where are the questions ? I don't see them here or in Slack... Thanks.

**Comment by gsouvik** [comment]
@WebDevJL 
The first round of dev on the menu is completed. Please review the functionality + code.

Also please refer to the shared doc for feature specifications we discussed earlier:
https://docs.google.com/document/d/18QJSCnzCCWxvNApofA3plf6M_eHjbzIR7-bgVO_HBmQ/edit

Shall get in touch with you on Slack tomorrow.
